<?php
require_once __DIR__ . '/../functions/permissions.php';
require_once __DIR__ . '/../functions/student_functions.php';
// allow both students and admins to view this page (admins may need to create missing student records)
requireLogin();

$current = getCurrentUser();
$student = null;
if ($current && isset($current['id'])) {
    // Prefer lookup by user_id if available
    $student = getStudentByUserId($current['id']);
}
// Fallback: try to match student_code == username (legacy behavior)
if (!$student && $current && isset($current['username'])) {
    $student = getStudentByCode($current['username']);
}
?>
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Hồ sơ sinh viên</title>
    <link rel="stylesheet" href="../css/home.css">
    <link rel="stylesheet" href="../css/user-theme.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        .profile-card {
            background: white;
            border-radius: 10px;
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
            overflow: hidden;
        }

        .profile-header {
            background: linear-gradient(135deg, #be93c5, #7bc6cc);
            color: white;
            padding: 2rem;
            text-align: center;
            position: relative;
        }

        .profile-avatar {
            width: 120px;
            height: 120px;
            border-radius: 50%;
            border: 4px solid white;
            margin: 0 auto 1rem;
            background: #fff;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .profile-avatar i {
            font-size: 4rem;
            color: #be93c5;
        }

        .profile-body {
            padding: 2rem;
        }

        .info-group {
            margin-bottom: 1.5rem;
            border-bottom: 1px solid #eee;
            padding-bottom: 0.5rem;
        }

        .info-label {
            color: #666;
            font-size: 0.9rem;
            margin-bottom: 0.25rem;
        }

        .info-value {
            font-size: 1.1rem;
            font-weight: 500;
            color: #333;
        }

        .department-badge {
            background: rgba(255, 255, 255, 0.2);
            padding: 0.5rem 1rem;
            border-radius: 20px;
            font-size: 0.9rem;
            margin-top: 0.5rem;
            display: inline-block;
        }

        @media (max-width: 768px) {
            .profile-header {
                padding: 1.5rem;
            }

            .profile-avatar {
                width: 100px;
                height: 100px;
            }

            .profile-body {
                padding: 1.5rem;
            }
        }
    </style>
</head>

<body class="bg-light">
    <?php include __DIR__ . '/user_menu.php'; ?>
    <div class="container my-4">

        <?php if (!$student): ?>
            <div class="alert alert-warning">
                <div class="d-flex align-items-center mb-3">
                    <i class="fas fa-exclamation-triangle me-3" style="font-size: 2rem; color: #856404;"></i>
                    <h4 class="mb-0">Không tìm thấy hồ sơ sinh viên</h4>
                </div>
                <?php if ($isOwner): ?>
                    <div class="collapse mt-3" id="proposeEditForm" style="display:none">
                        <!-- Inline edit will be generated by JS -->
                    </div>
                <?php endif; ?>
                <p>Không tìm thấy hồ sơ sinh viên tương ứng với tài khoản
                    <strong><?php echo htmlspecialchars($current['username'] ?? ''); ?></strong>.
                </p>
                <p><i class="fas fa-info-circle me-2"></i>Nguyên nhân thường gặp: tài khoản người dùng chưa được liên kết
                    với hồ sơ sinh viên (mã sinh viên khác nhau).</p>
                <p><i class="fas fa-hand-point-right me-2"></i>Vui lòng liên hệ quản trị viên để tạo hoặc cập nhật hồ sơ.
                </p>
                <?php if (function_exists('isAdmin') && isAdmin()): ?>
                    <a href="student/create_student.php" class="btn btn-primary mt-3">
                        <i class="fas fa-user-plus me-2"></i>Tạo hồ sơ sinh viên
                    </a>
                <?php endif; ?>
            </div>
        <?php else: ?>
            <div class="profile-card">
                <div class="profile-header">
                    <div class="profile-avatar">
                        <?php if (!empty($student['avatar_path'])): ?>
                            <img src="<?php echo htmlspecialchars($student['avatar_path']); ?>" alt="avatar" style="width:100%; height:100%; border-radius:50%; object-fit:cover;">
                        <?php else: ?>
                            <i class="fas fa-user-graduate"></i>
                        <?php endif; ?>
                    </div>
                    <h3 class="mb-2"><?php echo htmlspecialchars($student['full_name']); ?></h3>
                    <p class="mb-2">Mã sinh viên: <?php echo htmlspecialchars($student['student_code']); ?></p>
                    <div class="department-badge">
                        <i class="fas fa-building me-2"></i>
                        <?php echo htmlspecialchars($student['department_name']); ?>

                    </div>
                    <?php
                        $currentUser = getCurrentUser();
                        $isOwner = $currentUser && isset($currentUser['id']) && $student['user_id'] == $currentUser['id'];
                    ?>
                    <?php if ($isOwner): ?>
                        <div class="mt-3">
                            <button id="btnProposeEdit" class="btn btn-warning" type="button">
                                Đề xuất sửa thông tin
                            </button>
                        </div>
                    <?php endif; ?>
                </div>
                    <div class="profile-body">
                        <div class="row">
                            <div class="col-md-6">
                                <h6 class="mb-2 mt-2"><i class="fas fa-user me-2"></i>Thông tin cá nhân</h6>
                                <div class="info-group"><span class="info-label">Ngày sinh:</span> <span class="info-value"><?php echo htmlspecialchars($student['birth_date']); ?></span></div>
                                <div class="info-group"><span class="info-label">Giới tính:</span> <span class="info-value"><?php echo htmlspecialchars($student['gender']); ?></span></div>
                                <div class="info-group"><span class="info-label">Số điện thoại:</span> <span class="info-value"><?php echo htmlspecialchars($student['phone'] ?? ''); ?></span></div>
                                <div class="info-group"><span class="info-label">Số điện thoại phụ:</span> <span class="info-value"><?php echo htmlspecialchars($student['phone_alt'] ?? ''); ?></span></div>
                                <div class="info-group"><span class="info-label">Email:</span> <span class="info-value"><?php echo htmlspecialchars($student['email'] ?? ''); ?></span></div>
                                <div class="info-group"><span class="info-label">Email cá nhân:</span> <span class="info-value"><?php echo htmlspecialchars($student['student_email'] ?? ''); ?></span></div>
                                <div class="info-group"><span class="info-label">Quốc tịch:</span> <span class="info-value"><?php echo htmlspecialchars($student['nationality'] ?? ''); ?></span></div>
                                <div class="info-group"><span class="info-label">Dân tộc:</span> <span class="info-value"><?php echo htmlspecialchars($student['ethnicity'] ?? ''); ?></span></div>
                                <div class="info-group"><span class="info-label">Tôn giáo:</span> <span class="info-value"><?php echo htmlspecialchars($student['religion'] ?? ''); ?></span></div>
                                <h6 class="mb-2 mt-4"><i class="fas fa-id-card me-2"></i>Thông tin CCCD</h6>
                                <div class="info-group"><span class="info-label">Số CCCD:</span> <span class="info-value"><?php echo htmlspecialchars($student['cccd_number'] ?? ''); ?></span></div>
                                <div class="info-group"><span class="info-label">Nơi cấp:</span> <span class="info-value"><?php echo htmlspecialchars($student['cccd_place'] ?? ''); ?></span></div>
                                <div class="info-group"><span class="info-label">Ngày cấp:</span> <span class="info-value"><?php echo htmlspecialchars($student['cccd_issue_date'] ?? ''); ?></span></div>
                                <?php if (!empty($student['cccd_front_path']) || !empty($student['cccd_back_path'])): ?>
                                    <div class="info-group"><span class="info-label">Ảnh CCCD:</span>
                                        <div class="d-flex gap-2">
                                            <?php if (!empty($student['cccd_front_path'])): ?>
                                                <a href="<?php echo htmlspecialchars($student['cccd_front_path']); ?>" target="_blank"><img src="<?php echo htmlspecialchars($student['cccd_front_path']); ?>" alt="cccd front" style="max-width:120px; max-height:90px; object-fit:cover; border:1px solid #ddd; padding:2px;"></a>
                                            <?php endif; ?>
                                            <?php if (!empty($student['cccd_back_path'])): ?>
                                                <a href="<?php echo htmlspecialchars($student['cccd_back_path']); ?>" target="_blank"><img src="<?php echo htmlspecialchars($student['cccd_back_path']); ?>" alt="cccd back" style="max-width:120px; max-height:90px; object-fit:cover; border:1px solid #ddd; padding:2px;"></a>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                <?php endif; ?>
                                <h6 class="mb-2 mt-4"><i class="fas fa-graduation-cap me-2"></i>Học tập</h6>
                                <div class="info-group"><span class="info-label">Lớp:</span> <span class="info-value"><?php echo htmlspecialchars($student['class_name']); ?></span></div>
                                <div class="info-group"><span class="info-label">Chuyên ngành:</span> <span class="info-value"><?php echo htmlspecialchars($student['major'] ?? ''); ?></span></div>
                                <div class="info-group"><span class="info-label">Hệ đào tạo:</span> <span class="info-value"><?php echo htmlspecialchars($student['education_system'] ?? ''); ?></span></div>
                                <div class="info-group"><span class="info-label">Khóa học:</span> <span class="info-value"><?php echo htmlspecialchars($student['course_year'] ?? ''); ?></span></div>
                                <div class="info-group"><span class="info-label">Khóa tuyển sinh:</span> <span class="info-value"><?php echo htmlspecialchars($student['admission_batch'] ?? ''); ?></span></div>
                                <div class="info-group"><span class="info-label">Học lực lớp 12:</span> <span class="info-value"><?php echo htmlspecialchars($student['grade12_academic'] ?? ''); ?></span></div>
                                <div class="info-group"><span class="info-label">Hạnh kiểm lớp 12:</span> <span class="info-value"><?php echo htmlspecialchars($student['grade12_conduct'] ?? ''); ?></span></div>
                            </div>
                            <div class="col-md-6">
                                <h6 class="mb-2 mt-2"><i class="fas fa-map-marker-alt me-2"></i>Địa chỉ</h6>
                                <div class="info-group"><span class="info-label">Địa chỉ thường trú:</span> <span class="info-value"><?php echo htmlspecialchars($student['permanent_province'] ?? ''); ?>, <?php echo htmlspecialchars($student['permanent_ward'] ?? ''); ?>, <?php echo htmlspecialchars($student['permanent_address'] ?? ''); ?></span></div>
                                <div class="info-group"><span class="info-label">Địa chỉ hiện nay:</span> <span class="info-value"><?php echo htmlspecialchars($student['current_province'] ?? ''); ?>, <?php echo htmlspecialchars($student['current_ward'] ?? ''); ?>, <?php echo htmlspecialchars($student['current_address'] ?? ''); ?></span></div>
                                <div class="info-group"><span class="info-label">Nơi sinh:</span> <span class="info-value"><?php echo htmlspecialchars($student['birth_province'] ?? ''); ?>, <?php echo htmlspecialchars($student['birth_ward'] ?? ''); ?></span></div>
                                <h6 class="mb-2 mt-4"><i class="fas fa-university me-2"></i>Ngân hàng & ký túc xá</h6>
                                <div class="info-group"><span class="info-label">Ngân hàng:</span> <span class="info-value"><?php echo htmlspecialchars($student['bank_name'] ?? ''); ?> (<?php echo htmlspecialchars($student['bank_account'] ?? ''); ?>)</span></div>
                                <div class="info-group"><span class="info-label">Ký túc xá:</span> <span class="info-value">Địa chỉ: <?php echo htmlspecialchars($student['dorm_address'] ?? ''); ?><?php if (!empty($student['is_offcampus'])): ?> (Ngoại trú)<?php endif; ?></span></div>
                                <div class="info-group"><span class="info-label">Học kỳ/năm ở nội/ngoại trú:</span> <span class="info-value"><?php echo htmlspecialchars($student['residence_term'] ?? ''); ?> / <?php echo htmlspecialchars($student['residence_year'] ?? ''); ?></span></div>
                                <h6 class="mb-2 mt-4"><i class="fas fa-user-friends me-2"></i>Hoạt động đoàn/đảng</h6>
                                <div class="info-group"><span class="info-label">Đoàn viên:</span> <span class="info-value"><?php echo !empty($student['is_union_member']) ? 'Có' : 'Không'; ?></span></div>
                                <div class="info-group"><span class="info-label">Đảng viên:</span> <span class="info-value"><?php echo !empty($student['is_party_member']) ? 'Có' : 'Không'; ?></span></div>
                                <div class="info-group"><span class="info-label">Ngày vào Đoàn/Đảng:</span> <span class="info-value"><?php echo htmlspecialchars($student['join_date'] ?? ''); ?></span></div>
                                <h6 class="mb-2 mt-4"><i class="fas fa-user me-2"></i>Người báo tin / liên hệ</h6>
                                <div class="info-group"><span class="info-label">Người báo tin:</span> <span class="info-value"><?php echo htmlspecialchars($student['reporter_name'] ?? ''); ?> (<?php echo htmlspecialchars($student['reporter_phone'] ?? ''); ?>)</span></div>
                                <div class="info-group"><span class="info-label">Địa chỉ liên hệ:</span> <span class="info-value"><?php echo htmlspecialchars($student['contact_address'] ?? ''); ?></span></div>
                                <?php if (function_exists('isAdmin') && isAdmin()): ?>
                                    <div class="mt-3">
                                        <a href="views/student/edit_student.php?id=<?php echo intval($student['id']); ?>" class="btn btn-outline-primary">Sửa hồ sơ</a>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
            </div>
            <!-- Edit contact modal -->
            <div class="modal fade" id="editContactModal" tabindex="-1" aria-hidden="true">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">Sửa thông tin liên hệ</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <form method="POST" action="../handle/student_process.php">
                            <input type="hidden" name="action" value="self_edit">
                            <div class="modal-body">
                                <div class="row g-3">
                                    <div class="col-md-6">
                                        <label class="form-label">Số điện thoại</label>
                                        <input type="text" name="phone" class="form-control"
                                            value="<?php echo htmlspecialchars($student['phone'] ?? ''); ?>">
                                    </div>
                                    <div class="col-md-6">
                                        <label class="form-label">Email</label>
                                        <input type="email" name="email" class="form-control"
                                            value="<?php echo htmlspecialchars($student['email'] ?? ''); ?>">
                                    </div>
                                </div>
                                <div class="mt-3">
                                    <label class="form-label">Địa chỉ</label>
                                    <textarea name="address" class="form-control"
                                        rows="3"><?php echo htmlspecialchars($student['address'] ?? ''); ?></textarea>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Hủy</button>
                                <button type="submit" class="btn btn-primary">Lưu</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        <?php endif; ?>
    </div>
    <script>
        // Inline edit behavior for profile owner
        (function(){
            var btn = document.getElementById('btnProposeEdit');
            if (!btn) return;
            var profileBody = document.querySelector('.profile-body');
            var originalHtml = profileBody.innerHTML;
            var editing = false;


            function createInput(name, value, type){
                type = type || 'text';
                if (type === 'select') return null; // handled separately
                var inp = document.createElement('input');
                inp.className = 'form-control';
                inp.name = name;
                inp.value = value || '';
                if (type === 'date') inp.type = 'date';
                if (type === 'email') inp.type = 'email';
                return inp;
            }

            btn.addEventListener('click', function(){
                if (editing) return;
                editing = true;
                // build inline edit form using existing student data
                var s = <?php echo json_encode($student); ?>;
                var form = document.createElement('form');
                form.method = 'POST';
                form.action = '../handle/student_process.php';
                // hidden action/id
                var h1 = document.createElement('input'); h1.type='hidden'; h1.name='action'; h1.value='self_update_basic'; form.appendChild(h1);
                var h2 = document.createElement('input'); h2.type='hidden'; h2.name='id'; h2.value=<?php echo intval($student['id']); ?>; form.appendChild(h2);


                // layout: 2 columns, group fields
                var row = document.createElement('div'); row.className='row g-3';

                function addField(label, name, value, col, type) {
                    var c = document.createElement('div'); c.className = col;
                    var l = document.createElement('label'); l.className = 'form-label'; l.textContent = label;
                    var inp = createInput(name, value, type);
                    c.appendChild(l); c.appendChild(inp);
                    row.appendChild(c);
                }

                addField('Họ và tên', 'full_name', s.full_name, 'col-md-6');
                addField('Ngày sinh', 'birth_date', s.birth_date, 'col-md-3', 'date');
                // gender select
                var colGender = document.createElement('div'); colGender.className='col-md-3';
                var lblGender = document.createElement('label'); lblGender.className='form-label'; lblGender.textContent='Giới tính';
                var sel = document.createElement('select'); sel.className='form-select'; sel.name='gender';
                var opt0=document.createElement('option'); opt0.value=''; opt0.text='--Chọn--'; sel.appendChild(opt0);
                var opt1=document.createElement('option'); opt1.value='Nam'; opt1.text='Nam'; sel.appendChild(opt1);
                var opt2=document.createElement('option'); opt2.value='Nữ'; opt2.text='Nữ'; sel.appendChild(opt2);
                if (s.gender) sel.value = s.gender;
                colGender.appendChild(lblGender); colGender.appendChild(sel);
                row.appendChild(colGender);

                addField('Số điện thoại', 'phone', s.phone, 'col-md-4');
                addField('Số điện thoại phụ', 'phone_alt', s.phone_alt, 'col-md-4');
                addField('Email', 'email', s.email, 'col-md-4', 'email');
                addField('Email cá nhân', 'student_email', s.student_email, 'col-md-4', 'email');
                addField('Địa chỉ', 'address', s.address, 'col-md-8');

                // CCCD
                addField('Số CCCD', 'cccd_number', s.cccd_number, 'col-md-4');
                addField('Nơi cấp CCCD', 'cccd_place', s.cccd_place, 'col-md-4');
                addField('Ngày cấp CCCD', 'cccd_issue_date', s.cccd_issue_date, 'col-md-4', 'date');

                // Quốc tịch, dân tộc, tôn giáo
                addField('Quốc tịch', 'nationality', s.nationality, 'col-md-4');
                addField('Dân tộc', 'ethnicity', s.ethnicity, 'col-md-4');
                addField('Tôn giáo', 'religion', s.religion, 'col-md-4');

                // Học tập
                addField('Lớp', 'class_name', s.class_name, 'col-md-4');
                addField('Chuyên ngành', 'major', s.major, 'col-md-4');
                addField('Hệ đào tạo', 'education_system', s.education_system, 'col-md-4');
                addField('Khóa học', 'course_year', s.course_year, 'col-md-4');
                addField('Khóa tuyển sinh', 'admission_batch', s.admission_batch, 'col-md-4');
                addField('Học lực lớp 12', 'grade12_academic', s.grade12_academic, 'col-md-4');
                addField('Hạnh kiểm lớp 12', 'grade12_conduct', s.grade12_conduct, 'col-md-4');

                // Đoàn/Đảng
                // Checkbox for union/party member
                var colUnion = document.createElement('div'); colUnion.className='col-md-4 d-flex align-items-end';
                var checkUnion = document.createElement('input'); checkUnion.type='checkbox'; checkUnion.name='is_union_member'; checkUnion.value='1'; checkUnion.id='is_union_member';
                if (s.is_union_member && (s.is_union_member === 1 || s.is_union_member === '1')) checkUnion.checked = true;
                var lblUnion = document.createElement('label'); lblUnion.className='form-check-label ms-2'; lblUnion.htmlFor='is_union_member'; lblUnion.textContent='Đoàn viên';
                colUnion.appendChild(checkUnion); colUnion.appendChild(lblUnion);
                row.appendChild(colUnion);

                var colParty = document.createElement('div'); colParty.className='col-md-4 d-flex align-items-end';
                var checkParty = document.createElement('input'); checkParty.type='checkbox'; checkParty.name='is_party_member'; checkParty.value='1'; checkParty.id='is_party_member';
                if (s.is_party_member && (s.is_party_member === 1 || s.is_party_member === '1')) checkParty.checked = true;
                var lblParty = document.createElement('label'); lblParty.className='form-check-label ms-2'; lblParty.htmlFor='is_party_member'; lblParty.textContent='Đảng viên';
                colParty.appendChild(checkParty); colParty.appendChild(lblParty);
                row.appendChild(colParty);

                addField('Ngày vào Đoàn/Đảng', 'join_date', s.join_date, 'col-md-4', 'date');

                // Địa chỉ chi tiết
                addField('Tỉnh/Thành phố thường trú', 'permanent_province', s.permanent_province, 'col-md-4');
                addField('Xã/Phường thường trú', 'permanent_ward', s.permanent_ward, 'col-md-4');
                addField('Số nhà/thôn, xóm thường trú', 'permanent_address', s.permanent_address, 'col-md-4');
                addField('Tỉnh/Thành phố hiện nay', 'current_province', s.current_province, 'col-md-4');
                addField('Xã/Phường hiện nay', 'current_ward', s.current_ward, 'col-md-4');
                addField('Số nhà/thôn, xóm nơi ở hiện nay', 'current_address', s.current_address, 'col-md-4');
                addField('Tỉnh/Thành phố nơi sinh', 'birth_province', s.birth_province, 'col-md-4');
                addField('Xã/Phường nơi sinh', 'birth_ward', s.birth_ward, 'col-md-4');

                // Ngân hàng & ký túc xá
                addField('Tên ngân hàng', 'bank_name', s.bank_name, 'col-md-4');
                addField('Số tài khoản ngân hàng', 'bank_account', s.bank_account, 'col-md-4');
                addField('Địa chỉ ký túc xá', 'dorm_address', s.dorm_address, 'col-md-4');
                // is_offcampus select
                var colOff = document.createElement('div'); colOff.className='col-md-4';
                var lblOff = document.createElement('label'); lblOff.className='form-label'; lblOff.textContent='Sinh viên hiện ở ngoại trú';
                var selOff = document.createElement('select'); selOff.className='form-select'; selOff.name='is_offcampus';
                var optNo = document.createElement('option'); optNo.value='0'; optNo.text='Không'; selOff.appendChild(optNo);
                var optYes = document.createElement('option'); optYes.value='1'; optYes.text='Có'; selOff.appendChild(optYes);
                selOff.value = s.is_offcampus && (s.is_offcampus === 1 || s.is_offcampus === '1') ? '1' : '0';
                colOff.appendChild(lblOff); colOff.appendChild(selOff);
                row.appendChild(colOff);
                addField('Học kỳ ở nội/ngoại trú', 'residence_term', s.residence_term, 'col-md-4');
                addField('Năm học ở nội/ngoại trú', 'residence_year', s.residence_year, 'col-md-4');

                // Người báo tin
                addField('Người báo tin', 'reporter_name', s.reporter_name, 'col-md-4');
                addField('SĐT người báo tin', 'reporter_phone', s.reporter_phone, 'col-md-4');
                addField('Địa chỉ liên hệ', 'contact_address', s.contact_address, 'col-md-4');

                form.appendChild(row);

                var footer = document.createElement('div'); footer.className='mt-3 text-end';
                var btnCancel = document.createElement('button'); btnCancel.type='button'; btnCancel.className='btn btn-secondary me-2'; btnCancel.textContent='Hủy';
                var btnSave = document.createElement('button'); btnSave.type='submit'; btnSave.className='btn btn-primary'; btnSave.textContent='Lưu thay đổi';
                footer.appendChild(btnCancel); footer.appendChild(btnSave);
                form.appendChild(footer);

                // replace profileBody content with form
                profileBody.innerHTML = ''; profileBody.appendChild(form);

                btnCancel.addEventListener('click', function(){ profileBody.innerHTML = originalHtml; editing = false; });
            });
        })();
    </script>
</body>

</html>